import React from "react";
import "./App.css";
import MapButton from "./mapButton";
import InfoButton from "./infoButton";

function FireInfo() {
    return (
        <div className="App">
            <header className="App-header">
            <h1>DuckyProgramming Firms</h1>
            <h2>Wildfires</h2>
                <p className="limitedWidth">Wildfires are highly dangerous due to their destructive and unpredictable nature. They can spread rapidly, fueled by dry vegetation, strong winds, and high temperatures. The intense heat generated by wildfires can cause significant damage to ecosystems, homes, infrastructure, and wildlife. The thick smoke produced contains harmful pollutants and can pose serious health risks to people, particularly those with respiratory conditions. Wildfires also have far-reaching environmental consequences, contributing to air and water pollution, loss of biodiversity, and soil degradation. Learning the ins and outs of the causes of fires and the data that support it is a must for all communities and people.</p>
                <div className="simpleButton">
                    <MapButton />
                </div>
                <div className="simpleButton">
                    <InfoButton />
                </div>
            </header>
        </div>

    );
}

export default FireInfo;
